name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn test
      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2.0.3
        with:
          package-manager: yarn
          test-script: yarn jest --forceExit